### ISSUE TITLE
AU Linux kernel 2016 запрос на проверку Задание2 Шугаепов Ильнур

### ISSUE THREAD

**Issue by ilnurshug** [eabatalov/au-linux-kernel-spring-2016#2]
https://github.com/ilnurshug/au-linux-kernel-spring-2016/commit/c98e8d719b984be6e6ac19bdc714134c91086624

**Comment by eabatalov** [comment]
I've added some comments that would be better to fix.
If you want me to check the HW, then you need to assign this issue to me.

**Comment by ilnurshug** [comment]
Fix: https://github.com/ilnurshug/au-linux-kernel-spring-2016/commit/c98e8d719b984be6e6ac19bdc714134c91086624

I'm trying to follow steps from here: [https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/](url). But no matter what i can not assign this issue to you.
